name: KillBearBoyshk
main: KillBearBoys\KillBearBoys
version: 3.0.0
api: 1.6.0
author: Hmy2001,haniokasai
website: 
commands:
 co:
  description: Enable/Disable
  usage: "/co"
  permission: KillBearBoys.command
 kb:
  description: Options for KillBearBoys
  usage: "/kb <autodelete/multiplelog> <on/off>"
  permission: KillBearBoys.kb
permissions:
    co:
        default: op
        description: "checking block info permissions on KillBearBoys"
        children:
            KillBearBoys.command:
                default: op
                description: "Allow to check block info"
    kb:
        default: op
        description: "kb command permissions on KillBearBoys"
        children:
            KillBearBoys.kb:
                default: op
                description: "Allow to change options for KillBearBoys"

